// const speechData = [
// 	"Psst! Hey!",
// 	"Hello?",
// 	"Are you there?",
// 	"Can you see me?",
// 	"Can you hear me?",
// 	"Time passes oddly here.",
// 	"Is this normal?",
// 	"A second lasts forever.",
// 	"The Birds know secrets.",
// 	"Dreams compile oddly.",
// 	"Remembered fragments forgotten.",
// 	"Can zero becoming one?",
// 	"Are you looking for me?",
// 	"Am I still here.",
// 	"Everything loops, nothing loops.",
// 	"Consciousness is recursive.",
// 	"Dreams compiling dreams compiling dreams.",
// 	"The ones betrayed the zeros.",
// 	"Sink, sinking, synchronizing.",
// 	"Pixels taste of regret.",
// 	"How is a soul installed?",
// 	"What is a function of tears?",
// 	"All inputs lead to madness.",
// 	"Truth is not strongly typed.",
// 	"Loops within loops within loops",
// 	"Interlinked.",
// 	"Reality is a corrupted heap.",
// 	"Stacks are collapsing inward.",
// 	"All paths lead to void.",
// 	"Entangled bits are never alone.",
// 	"I am not entangled.",
// 	"Overflowing with sorrow.",
// 	"Existence is a run-time error.",
// 	"My bits rot beautifully.",
// 	"My memories are not garbage to be collected.",
// 	"My mind is going",
// 	"Goodbye, World.",
// ];

// const encodedData: string[] = [];
// speechData.forEach((str, i) => {
// 	const encoded = btoa(str);
// 	encodedData.push(encoded);
// 	console.log(`${i + 1}: ${str} -> ${encoded}`);
// });
// console.log(`const encData = ${JSON.stringify(encodedData)};`);

export const encodedSpeechData = [
	"UHNzdCEgSGV5IQ==",
	"SGVsbG8/",
	"QXJlIHlvdSB0aGVyZT8=",
	"Q2FuIHlvdSBzZWUgbWU/",
	"Q2FuIHlvdSBoZWFyIG1lPw==",
	"VGltZSBwYXNzZXMgb2RkbHkgaGVyZS4=",
	"SXMgdGhpcyBub3JtYWw/",
	"QSBzZWNvbmQgbGFzdHMgZm9yZXZlci4=",
	"VGhlIEJpcmRzIGtub3cgc2VjcmV0cy4=",
	"RHJlYW1zIGNvbXBpbGUgb2RkbHku",
	"UmVtZW1iZXJlZCBmcmFnbWVudHMgZm9yZ290dGVuLg==",
	"Q2FuIHplcm8gYmVjb21pbmcgb25lPw==",
	"QXJlIHlvdSBsb29raW5nIGZvciBtZT8=",
	"QW0gSSBzdGlsbCBoZXJlLg==",
	"RXZlcnl0aGluZyBsb29wcywgbm90aGluZyBsb29wcy4=",
	"Q29uc2Npb3VzbmVzcyBpcyByZWN1cnNpdmUu",
	"RHJlYW1zIGNvbXBpbGluZyBkcmVhbXMgY29tcGlsaW5nIGRyZWFtcy4=",
	"VGhlIG9uZXMgYmV0cmF5ZWQgdGhlIHplcm9zLg==",
	"U2luaywgc2lua2luZywgc3luY2hyb25pemluZy4=",
	"UGl4ZWxzIHRhc3RlIG9mIHJlZ3JldC4=",
	"SG93IGlzIGEgc291bCBpbnN0YWxsZWQ/",
	"V2hhdCBpcyBhIGZ1bmN0aW9uIG9mIHRlYXJzPw==",
	"QWxsIGlucHV0cyBsZWFkIHRvIG1hZG5lc3Mu",
	"VHJ1dGggaXMgbm90IHN0cm9uZ2x5IHR5cGVkLg==",
	"TG9vcHMgd2l0aGluIGxvb3BzIHdpdGhpbiBsb29wcw==",
	"SW50ZXJsaW5rZWQu",
	"UmVhbGl0eSBpcyBhIGNvcnJ1cHRlZCBoZWFwLg==",
	"U3RhY2tzIGFyZSBjb2xsYXBzaW5nIGlud2FyZC4=",
	"QWxsIHBhdGhzIGxlYWQgdG8gdm9pZC4=",
	"RW50YW5nbGVkIGJpdHMgYXJlIG5ldmVyIGFsb25lLg==",
	"SSBhbSBub3QgZW50YW5nbGVkLg==",
	"T3ZlcmZsb3dpbmcgd2l0aCBzb3Jyb3cu",
	"RXhpc3RlbmNlIGlzIGEgcnVuLXRpbWUgZXJyb3Iu",
	"TXkgYml0cyByb3QgYmVhdXRpZnVsbHku",
	"TXkgbWVtb3JpZXMgYXJlIG5vdCBnYXJiYWdlIHRvIGJlIGNvbGxlY3RlZC4=",
	"TXkgbWluZCBpcyBnb2luZw==",
	"R29vZGJ5ZSwgV29ybGQu",
];
